//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressProof
    {
        public AddressProof()
        {
            this.ShopKeeperDetails = new HashSet<ShopKeeperDetail>();
        }
    
        public int ID { get; set; }
        public string AddressProof1 { get; set; }
    
        public virtual ICollection<ShopKeeperDetail> ShopKeeperDetails { get; set; }
    }
}
