//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public string PhoneNumber { get; set; }
        public string BeneficiaryPhoneNumber { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> TransferLimit { get; set; }
        public long SNo { get; set; }
    }
}
