//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangerUpdatedDetail
    {
        public Nullable<long> ShopKeeperAccountNumber { get; set; }
        public Nullable<long> CustomerAccountNumber { get; set; }
        public string PreviousValue { get; set; }
        public string UpdatedField { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int UpdatedDetailId { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber1 { get; set; }
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber2 { get; set; }
    }
}
