//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangerWrongNFCEntry
    {
        public decimal SNO { get; set; }
        public string MobileNumber { get; set; }
        public long NFC { get; set; }
    }
}
