//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangerBlockList
    {
        public string MobileNumber { get; set; }
        public bool Blocked { get; set; }
        public bool SemiBlocked { get; set; }
        public int Attempts { get; set; }
    }
}
