//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public CustomerDetail()
        {
            this.ChangerUpdatedDetails = new HashSet<ChangerUpdatedDetail>();
        }
    
        public string PhoneNumber { get; set; }
        public long CustomerAccountNumber { get; set; }
        public int Password { get; set; }
        public long NFCTagID { get; set; }
        public int AccountStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CustomerName { get; set; }
        public int Privileges { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<ChangerUpdatedDetail> ChangerUpdatedDetails { get; set; }
        public virtual CustomerAccountDetail CustomerAccountDetail { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserPrivilege UserPrivilege { get; set; }
    }
}
