//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccountDetail
    {
        public long CustomerAccountNumber { get; set; }
        public decimal Balance { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
