//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public int SNo { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsShopKeeper { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsDealer { get; set; }
    }
}
