//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public long OTPNumber { get; set; }
        public long CustomerAccountnumber { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Hits { get; set; }
        public string TransactionID { get; set; }
        public long ShopkeeperAccountNumber { get; set; }
        public int TID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual CustomerTransactionDetail CustomerTransactionDetail { get; set; }
        public virtual ShopKeeperTransactionDetail ShopKeeperTransactionDetail { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
