//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopKeeperAccountDetail
    {
        public long ShopKeeperAccountNumber { get; set; }
        public Nullable<decimal> SenderBalance { get; set; }
        public Nullable<decimal> ReceiverBalance { get; set; }
        public int ShopKeeperAccountNumberID { get; set; }
    
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber1 { get; set; }
    }
}
