//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopKeeperRechargeDetail
    {
        public Nullable<long> ShopKeeperAccountNumber { get; set; }
        public Nullable<decimal> RechargeAmount { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long SNo { get; set; }
    
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber1 { get; set; }
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber2 { get; set; }
    }
}
