//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopKeeperSmartCardMaster
    {
        public long ShopKeeperAccountNumber { get; set; }
        public long SmartCardSerialNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SmartCardSerialNumberStatus { get; set; }
        public int ShopKeeperSmartCardID { get; set; }
    
        public virtual ShopKeeperAccountNumber ShopKeeperAccountNumber1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
