//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopKeeperAccountNumber
    {
        public ShopKeeperAccountNumber()
        {
            this.ChangerUpdatedDetails = new HashSet<ChangerUpdatedDetail>();
            this.ChangerUpdatedDetails1 = new HashSet<ChangerUpdatedDetail>();
            this.ShopKeeperAccountDetails = new HashSet<ShopKeeperAccountDetail>();
            this.ShopKeeperRechargeDetails = new HashSet<ShopKeeperRechargeDetail>();
            this.ShopKeeperRechargeDetails1 = new HashSet<ShopKeeperRechargeDetail>();
            this.ShopKeeperDetails = new HashSet<ShopKeeperDetail>();
            this.ShopKeeperSmartCardMasters = new HashSet<ShopKeeperSmartCardMaster>();
            this.ShopKeeperTerminalDetails = new HashSet<ShopKeeperTerminalDetail>();
        }
    
        public long ShopKeeperAccountNumber1 { get; set; }
        public string SenderAccountNumber { get; set; }
        public string ReceiverAccountNumber { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<ChangerUpdatedDetail> ChangerUpdatedDetails { get; set; }
        public virtual ICollection<ChangerUpdatedDetail> ChangerUpdatedDetails1 { get; set; }
        public virtual ICollection<ShopKeeperAccountDetail> ShopKeeperAccountDetails { get; set; }
        public virtual ICollection<ShopKeeperRechargeDetail> ShopKeeperRechargeDetails { get; set; }
        public virtual ICollection<ShopKeeperRechargeDetail> ShopKeeperRechargeDetails1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<ShopKeeperDetail> ShopKeeperDetails { get; set; }
        public virtual ICollection<ShopKeeperSmartCardMaster> ShopKeeperSmartCardMasters { get; set; }
        public virtual ICollection<ShopKeeperTerminalDetail> ShopKeeperTerminalDetails { get; set; }
    }
}
