//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangerMints.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.OTPs = new HashSet<OTP>();
        }
    
        public int TID { get; set; }
        public string TTYPE { get; set; }
    
        public virtual ICollection<OTP> OTPs { get; set; }
    }
}
